sudo: false
language: go
go:
  - master
notifications:
  email: false
  slack:
    secure: w0HbZpT+lmOeF9oEml8pV2Ognsnbf8ZdZ7elxZARvGSkEcHCxm1u+ytkn8ycMlL0AZ9xXuZCLOtYfCeOLRBp5libHdf3PE8CbRyWJy2KQ7rTYN/OTH6rbcONw5O6pof141XaZP4lD5OQePHuNeHghYNSOAq4g24dQ7hiMfxdwOMlairTjeccjVYXElaSpJrHP4IednkJVgk4d5AIrwgsRAph/wF1LYRdYPun7DEP1FYZtE4hEzkuwF7lkJ79wRtMKQd9m21LVSOu4czFuw5jPuHnNe01H/MdWFAz4q3m9qN6klOORBDIGO536iL7JMasdX90vUR0K6QN4icYgUbTL7F1Zz7tRML3xAzcY5+y9F9bigkSs3DzJ/JG/l1khPRM15I/sN5poxUQukBJi6+prkSx51E/BEgp/oMGtg55iRJo+s5hB6Y0gKs5hykF9nxKP/vXfMGeoquDTc7bpRlmNUed+Ifu0BC2fgOSgYVbuoBkTFel1aiviFptsVekxVMCp1f2PbGdzuQ+t7IvMXsgfrcJLPY1x2hEc12N4oF6KhyjBBa1ATjVjQCsBLF+ZQCZONAt8MF0uCzBiN6u9H15MCGI87PWIkSf22vjfIKduFyvcHsfIc8Ub+bTCHO6oOaKPvTFTv3FVd4XkV6WonrSEz5GKQyx3YR16ppgusV4EVI=
go_import_path: github.com/gouvinb/go-microservice
install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/lint/golint
script: make deps test
